namespace Larva.Tools
{
    public class LocalizationTextKeys
    {
        public enum LocalizationMenuTextKeys
        {
            StartGame,
            HowPlay,
            LarvaHouse,
            Settings,
            Exit
        }
        public enum LocalizationInstructionsTextKeys
        {
            Instructions,
            GoodLeafs,
            BadLeafs,
            Obstacles,
            Back
        }
        public enum LocalizationSettingsTextKeys
        {
            Language,
            Sounds,
            Music,
            ScreenResolution,
            Fullscreen,
            Back,
            GamePanel,
            AudioPanel,
            VideoPanel,
            GameMode,
            SimpleMode,
            RealMode,
            SimpleModeInformation,
            RealModeInformation,
            ChooseFeedDay,
            Monday,
            Tuesday,
            Wednesday,
            Thursday,
            Friday,
            Saturday,
            Sunday,
            DayTime,
            Auto,
            Day,
            Evening,
            Night
        }
        public enum LocalizationGameTextKeys
        {
            Continue,
            Restart,
            MainMenu,
            YouScore
        }
        public enum LocalizationHouseTextKeys
        {
            Outside,
            MainHall,
            Bedroom,
            ChildrenRoom,
            Kitchen,
            NotBuilt,
            BuiltFor,
            Built,
            HavetBedroom,
            HavetKitchen,
            NotEnought,
            Head,
            Body,
            ChangeSkin,
            Close,
            Partner,
            Child,
            Add,
            For,
            Cancel,
            HavetPartner,
            FamilyEat
        }
        public enum LocalizationWardrobeTextKeys
        {
            Head,
            Body,
            ChangeSkin,
            Close
        }
    }
}